### ISSUE TITLE
Add makefile

### ISSUE THREAD

**Issue by alexandre** [alexandre/til#7]
Adding the following commands:

## `make venv`
_create a virtualenv and install poetry_

* Create a virtualenv => `python3 -m venv venv`
* Install poetry => `source venv/bin/activate; pip install poetry`

You can find some ideas about using a virtualenv in a Makefile context here:
https://stackoverflow.com/questions/24736146/how-to-use-virtualenv-in-makefile

## `make install`
_install the project_

* Install the project using poetry => `poetry install`
It will install the dev. deps too, but I think for now it's ok.

## `make test`
_run all the tests_

* Run tests using poetry: `poetry run pytest`

**Comment by NicolasFrancaX** [comment]
I can create this Makefile.

Can you send me the commands to execute each of these statements?

**Comment by NicolasFrancaX** [comment]
I think this issue have https://github.com/alexandre/til/issues/6 dependent.

**Comment by alexandre** [comment]
@NicolasFrancaX , done!
I did update the description :]

**Comment by NicolasFrancaX** [comment]
What you think about split this issues into 2, one with more focus in create a basic Makefile without Docker stuffs and another updating this Makefile with Docker stuffs?

**Comment by alexandre** [comment]
I think it's a good idea

**Comment by NicolasFrancaX** [comment]
I just created a new issue https://github.com/alexandre/til/issues/8 about this.

Can you delete the part of text about docker stuffs?
